### ISSUE TITLE
Migration Workflow

### ISSUE THREAD

**Issue by glucrypto** [Ecto-Finance/specto#10]
Workflow for signing in and Migration

1. When accessing site for the first time - user should be prompted with a Sign-in button on upper right corner.
2. On Click of sign in button - Normal metamask workflow to login to MM / connect to Specto
3. On successful sign in there should now be a migration button present. On click of migration - user should be able to enter contract address and hit 'send'.
4. On click of send - query opensea for the collection data.
5. The collection data then needs to be saved to IPFS.
6. Once saved to IPFS it then needs to be passed to the 'FollowerURI' field in the `profilepictureURI` graphql mutation.

**Comment by glucrypto** [comment]
@hobbescodes 

Pinata Workflow:

1. Install and setup: https://docs.pinata.cloud/pinata-node-sdk
2. pin json to ipfs: https://docs.pinata.cloud/pinata-node-sdk#pinjsontoipfs
3. The resulting hash should be saved in profilePictureURI as `ipfs://<IPFS_HASH>`

**Comment by hobbescodes** [comment]
Finished 1-4 on the workflow. Will work on pinning to IPFS and saving the resulting has tonight.

**Comment by glucrypto** [comment]
1-4 done in  #2817c9f

**Comment by hobbescodes** [comment]
Issue resolved!
